version: '3.6'
services:
  test_app:
      build:
        context: .
        dockerfile: ./docker/app/Dockerfile
        args:
          - NOVA_USER="user@example.com"
      volumes:
        - test-app-data:/var/www/app
      networks:
        - internet
  test_nginx:
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - test-app-data:/var/www/app
        - test-nginx-log:/var/log/nginx
      external_links:
        - test_app
      depends_on:
        - test_app
      networks:
        - internet
networks:
  internet:
volumes:
  test-app-data:
  test-nginx-log:
